SimpleMVCdapper/Controllers/CustomersController.cs
using SimpleMVCdapper.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SimpleMVCdapper.Services;
using Dapper;

namespace SimpleMVCdapper.Controllers
{
    public class CustomersController : Controller
    {
        public ActionResult Index()
        {
            CustomerService List = new CustomerService();
            return View(List.AllCustList().ToList());
        }

        [HttpGet][ActionName("AddCust")]
        public ActionResult AddCust_Get()
        {
            return View();
        }

        [HttpPost][ActionName("AddCust")]
        public ActionResult AddCust_Post(Customerinfo NewCust)
        {
            CustomerService New = new CustomerService();
            New.AddCust(NewCust);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateCust(long id)
        {
            CustomerService edit = new CustomerService();

            Customerinfo info = edit.AllCustList().Single(cust => cust.ID == id);
            return View(info);

            //return View(edit.GetCust(id));
        }

        [HttpPost]
        public ActionResult UpdateCust(Customerinfo Update)
        {
            CustomerService edit = new CustomerService();
            edit.UpdateCust(Update);
            return RedirectToAction("Index");
        }

        public ActionResult Details(long id)
        {
            CustomerService details = new CustomerService();
            Customerinfo info = details.AllCustList().Single(cust => cust.ID == id);
            return View(info);
        }

        [HttpGet]
        public ActionResult Delete(long id)
        {
            CustomerService delete = new CustomerService();
            Customerinfo info = delete.AllCustList().Single(cust => cust.ID == id);
            return View(info);
        }

        [HttpPost]
        public ActionResult Delete(Customerinfo delete)
        {
            CustomerService customerService = new CustomerService();
            customerService.Delete(delete);
            return RedirectToAction("Index");
        }
	}
}

SimpleMVCdapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            @*<div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>*@
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Customers List", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Add Customer", "AddCust", "Customers")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <center><p>&copy; @DateTime.Now.Year - ASP.NET MVC Application</p></center>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>